### ISSUE TITLE
the new pom.xml content for kafka 0.7.2 sink

### ISSUE THREAD

**Issue by 383124397** [baniuyao/flume-ng-kafka-sink#8]
if you do package under the original pom.xml, you could get some issues, just like too many license, etc.
now I supply a new dependence pom.xml for this cleared kafka07 sink project to my friend - Frank. thanks.
ps: just remember package command is "mvn assembly:assembly -DskipTests=true"
=======================Gorgeous split line===========================
![1](https://cloud.githubusercontent.com/assets/4112460/5533793/da91ae30-8a8a-11e4-9343-65c546442214.png)
![2](https://cloud.githubusercontent.com/assets/4112460/5533794/da96fde0-8a8a-11e4-9a8b-f641445cec79.png)

================================================================

**Comment by hzruandd** [comment]
hello, can you share the jar package with us?

**Comment by yrjsg** [comment]
@hzruandd this project has been merged into flume release branch. Kafka source/sink is available in flume now. What you need to do is download flume and enjoy it:)
